version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_started
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: example
            MYSQL_DB: wx_assistant
            MYSQL_PORT: 3306
            REDIS_HOST: redis
            REDIS_PORT: 6379
            GIN_MODE: release
            # REDIS_PASSWORD:
            AI_KEY: { { AI_KEY } }
            GAO_DE_KEY: { { GAO_DE_KEY } }
            TZ: Asia/Shanghai

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: wx_assistant
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 5s
            timeout: 5s
            retries: 10
        ports:
            - '3307:3306'
        volumes:
            - mysql-data:/var/lib/mysql

    redis:
        image: redis:6.0
        ports:
            - '6379:6379'

volumes:
    mysql-data:
