version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        env_file:
            - .env
        environment:
            GIN_MODE: release
            TZ: Asia/Shanghai
